title: Grupo de Pesquisa 
description: Departamento de Estatística - UFLA.
remote_theme: mmistakes/minimal-mistakes
text-align: justify
<div style="text-align: justify">
github: 
is_project_page: false
plugins:
  - jekyll-remote-theme

