

theme: minimal-mistakes-jekyll
gem "minimal-mistakes-jekyll"
source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
remote_theme: "mmistakes/minimal-mistakes@4.18.1"
jekyll-include-cache

